--when.repositories = ["~/src/freebsd-src", "~/src/freebsd-doc", "~/src/freebsd-ci"]

[templates]
#draft_commit_description = '''
#concat(
#  coalesce(description, default_commit_description, "\n"),
#  surround(
#    "\nJJ: This commit contains the following changes:\n", "",
#    indent("JJ:    ", diff.stat(72))))'''

commit_trailers = '''
format_signed_off_by_trailer(self)
++ Sponsored by: The FreeBSD Foundation'''
