--when.repositories = ["~/f"]

[user]
name = "Siva Mahadevan"
email = "siva@FreeBSD.org"

[template-aliases]
default_commit_description = '''
"
Reviewed by:
Approved by:
Signed-off-by:	Siva Mahadevan <siva@FreeBSD.org>
Sponsored by:	The FreeBSD Foundation
"
'''

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:    ", diff.stat(72))))
'''

duplicate_description = '''
concat(
  description,
  "\n(cherry picked from commit ", commit_id, ")"
)
'''
