[ui]
default-command = "log"
pager = "less -Ri"

[user]
name = "Siva Mahadevan"
email = "me@svmhdvn.name"

[git]
push = "origin"
fetch = "upstream"
colocate = false
write-change-id-header = true

[revset-aliases]
my_unbookmarked = "children(main) ~ ancestors(bookmarks()) ~ empty()"
