[user]
name = "Siva Mahadevan"
email = "me@svmhdvn.name"

[ui]
default-command = "log"
diff-formatter = ":git"
#diff-editor = "meld-3"

[git]
push = "origin"
fetch = "upstream"
colocate = false
write-change-id-header = true

[revset-aliases]
my_unbookmarked = "children(main) ~ ancestors(bookmarks()) ~ empty()"

[remotes.origin]
auto-track-bookmarks = "*"

[remotes.upstream]
auto-track-bookmarks = "main"
